---
# ───────────────
# Prerequisites:
# ───────────────
# python and ansible must be installed
# ansible-galaxy collection install cisco.ios junipernetworks.junos ansible.posix ansible.netcommon
# ansible-galaxy collection install community.general
# Make sure SSH is enabled on Cisco and juniper devices
# Make sure Netconf is enabled on juniper devices
# ───────────────
# ~/.ansible.cfg should have:
# ───────────────
# [defaults]
# host_key_checking = False
# vault_password_file = ~/ansible-netauto/.ansible_vault_pass.txt
# inventory = ~/ansible-netauto/backup_yaml_files/inventory.yml
# ───────────────
# Ansible Vault Notes:
# ───────────────
# ansible-vault encrypt inventory.yml --vault-password-file ~/ansible-netauto/.ansible_vault_pass.txt
# ansible-vault view inventory.yml --vault-password-file ~/ansible-netauto/.ansible_vault_pass.txt
# ansible-vault edit inventory.yml --vault-password-file ~/ansible-netauto/.ansible_vault_pass.txt
# run manual ansible-playbook playbook.yml --ask-vault-pass
# ───────────────
# Juniper Notes:
# ───────────────
# Ensure these are set on each Junos device:
# set system services ssh root-login allow
# set system services netconf ssh
# For older juniper devices set system services netconf rfc-compliant
# ───────────────
# GitHub Notes:
# ───────────────
# cd ~/network-programmability
# git init
# git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git
# git checkout -b main


- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Create archive and current backup directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ lookup('env', 'HOME') }}/network-programmability/backups/archive/{{ ansible_date_time.date }}"
        - "{{ lookup('env', 'HOME') }}/network-programmability/backups/current"
  run_once: true


# ===================== CISCO ROUTERS =====================

- hosts: Cisco_Routers
  gather_facts: no
  tasks:
    - name: Backup IOS config
      cisco.ios.ios_command:
        commands: show run
      register: config

    - name: Save IOS config to dated archive
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/archive/{{ hostvars.localhost.DTG }}/{{ inventory_hostname }}-{{ hostvars.localhost.DTG }}-config.txt"

    - name: Save IOS config to current/ for diffing
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/current/{{ inventory_hostname }}-config.txt"

- hosts: Cisco_Routers
  gather_facts: no
  vars:
    command_list:
      - show version
      - show ip interface brief
      - show interfaces
      - show ip route
      - show ip protocols
      - show cdp neighbors detail
      - show lldp neighbors detail
      - show clock
      - show users
      - show boot
      - show int stat
      - show arp
  tasks:
    - name: Run the SHOW commands and save output
      cisco.ios.ios_command:
        commands: "{{ command_list }}"
      register: showoutput

    - name: Save show output to dated archive
      template:
        src: template.j2
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/archive/{{ hostvars.localhost.DTG }}/{{ inventory_hostname }}-{{ hostvars.localhost.DTG }}-showoutput.txt"

    - name: Save show output to current/ for diffing
      template:
        src: template.j2
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/current/{{ inventory_hostname }}-showoutput.txt"


# ===================== CISCO SWITCHES =====================

- hosts: Cisco_Switches
  gather_facts: no
  tasks:
    - name: Backup Catalyst Switch config to dated archive
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}-{{ hostvars.localhost.DTG }}-config.txt"
          dir_path: "{{ lookup('env', 'HOME') }}/network-programmability/backups/archive/{{ hostvars.localhost.DTG }}"

    - name: Backup Catalyst Switch config to current/ for diffing
      cisco.ios.ios_command:
        commands: show running-config
      register: switch_config

    - name: Save current config to current/ directory
      copy:
        content: "{{ switch_config.stdout[0] }}"
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/current/{{ inventory_hostname }}-config.txt"

- hosts: Cisco_Switches
  gather_facts: no
  vars:
    command_list:
      - show version
      - show vlan brief
      - show interfaces status
      - show interfaces description
      - show interfaces
      - show ip interface brief
      - show cdp neighbors detail
      - show lldp neighbors detail
      - show spanning-tree
      - show mac address-table
      - show arp
      - show clock
      - show users
      - show boot
  tasks:
    - name: Run the SHOW commands and save output
      cisco.ios.ios_command:
        commands: "{{ command_list }}"
      register: showoutput

    - name: Save show output to dated archive
      template:
        src: template.j2
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/archive/{{ hostvars.localhost.DTG }}/{{ inventory_hostname }}-{{ hostvars.localhost.DTG }}-showoutput.txt"

    - name: Save show output to current/ for diffing
      template:
        src: template.j2
        dest: "{{ lookup('env', 'HOME') }}/network-programmability/backups/current/{{ inventory_hostname }}-showoutput.txt"

# ===================== JUNIPER CONFIGURATION OUTPUT =====================
- hosts: Juniper
  gather_facts: no
  connection: netconf

  vars:
    archive_dir: "{{ lookup('env','HOME') }}/network-programmability/backups/archive/{{ hostvars['localhost']['DTG'] | trim }}"
    current_dir: "{{ lookup('env','HOME') }}/network-programmability/backups/current"

  tasks:
    - name: Ensure archive and current backup directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ archive_dir }}"
        - "{{ current_dir }}"

    - name: Run SHOW Config command for Juniper
      junipernetworks.junos.junos_command:
        commands:
          - show configuration
      register: juniper_config

    - name: Save config to dated archive directory
      copy:
        content: "{{ juniper_config.stdout | join('\n') | default('No output from device') }}"
        dest: "{{ archive_dir }}/{{ inventory_hostname }}-{{ hostvars['localhost']['DTG'] | trim }}-config.txt"

    - name: Save config to current directory for diffing
      copy:
        content: "{{ juniper_config.stdout | join('\n') | default('No output from device') }}"
        dest: "{{ current_dir }}/{{ inventory_hostname }}-config.txt"

# ===================== JUNIPER SHOW OUTPUT =====================
- name: JUNIPER SHOW OUTPUT
  hosts: Juniper
  gather_facts: no
  connection: netconf

  collections:
    - junipernetworks.junos

  vars:
    DTG: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    archive_dir: "{{ lookup('env','HOME') }}/network-programmability/backups/archive/{{ DTG }}"
    current_dir: "{{ lookup('env','HOME') }}/network-programmability/backups/current"
    junos_rpcs:
      - { rpc: get-software-information }
      - { rpc: get-system-uptime-information }
      - { rpc: get-interface-information }
      - { rpc: get-route-summary-information }
      - { rpc: get-commit-information }
      - { rpc: get-commit-revision-information }
      - { rpc: get-alarm-information }

  tasks:
    - name: Ensure archive and current directories exist
      file:
        path: "{{ item }}"
        state: directory
      delegate_to: localhost
      loop:
        - "{{ archive_dir }}"
        - "{{ current_dir }}"

    - name: Run Junos RPC commands
      junipernetworks.junos.junos_rpc:
        rpc: "{{ item.rpc }}"
        output: xml
      loop: "{{ junos_rpcs }}"
      register: rpc_output

    - name: Save RPC output to archive
      template:
        src: junos_output.j2
        dest: "{{ archive_dir }}/{{ inventory_hostname }}-{{ DTG }}-showoutput.txt"
      vars:
        showoutput: "{{ rpc_output }}"
      delegate_to: localhost

    - name: Save RPC output to current
      template:
        src: junos_output.j2
        dest: "{{ current_dir }}/{{ inventory_hostname }}-showoutput.txt"
      vars:
        showoutput: "{{ rpc_output }}"
      delegate_to: localhost


# ===================== GITHUB BACKUP =====================

- name: Commit and push backup files to GitHub
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Stage backup changes
      shell: |
        cd ~/network-programmability
        git add backups/
      args:
        executable: /bin/bash

    - name: Commit backup with timestamp
      shell: |
        cd ~/network-programmability
        git commit -m "Backup {{ ansible_date_time.date }} {{ ansible_date_time.time }}"
      args:
        executable: /bin/bash
      ignore_errors: yes  # stops failure if there's nothing to commit (changed)

    - name: Push to GitHub
      shell: |
        cd ~/network-programmability
        git push origin main
      args:
        executable: /bin/bash
